### PR TITLE
Add `WavReader::seek_sample` method

### LINKED ISSUE #18: Add a `WavReader` method for seeking to the start of the audio data?
I'm currently attempting to implement an Iterator that cycles over a WAV file using `WavReader` in a personal project and something along these lines would be super helpful.

I can imagine a more general seeking implementation might also be useful for users who want to jump to a certain location within a file (e.g. a user clicks the timeline within a music player application). Rather than seeking in bytes as the `Seek` trait does, I picture this API would allow for seeking in samples (where `0` would be the first sample and `wav_reader.len()` would be the end).

I'm going to have a go at implementing this now but thought I'd post an issue in case you are around to share your thoughts sooner :)

### PR DESCRIPTION
**Pull request by mitchmindtree**
This adds a method to WavReader that allows the user to seek to a given
sample position within the file.

This method requires that the inner reader `R` implements `io::Seek`.

The given sample position represents the number of samples from the
beginning of the audio data. Thus the given sample position should not
exceed the length of the file in samples (returned by `len()`). The
behaviour when seeking beyond `len()` depends on the reader's `Seek`
implementation.

A test for the new method is included at the bottom of the module.

This closes #18.

### CODE REVIEW

**Comment by ruuda** [comment]
Looks good to me, thanks for doing this!

One note: I think it might be more convenient for `seek` to take a time point rather than a sample number. If you implement something like a seek bar by seeking to a fraction of `reader.len()`, you might end up at a sample that is not a multiple of the number of channels. In the case of a stereo file that would effectively swap the channels. When seeking to a time, maximum value would be `reader.duration() - 1` rather than `reader.len()`. What do you think?

**Comment by zyvitski** [comment]
Would it be a good idea to have different seek modes? Like seek from start, from end and from current position? In the same fashion that libsndfile uses? Either over separate functions or via a flag?

**Comment by mitchmindtree** [comment]
@ruuda I'm happy to go either way - I guess the trade-off with using a a time-based seek is that the user wouldn't be able to seek to a specific channel index. That said, they could still reach it by seeking and then iterating to the channel. Maybe use-cases for this are rare enough that it wouldn't be an issue anyway! 

@zyvitski I'm happy to add this. Perhaps we could declare a `SeekFrom` enum (following the `std::io::SeekFrom` convention) to use as an argument to `seek_sample`? I'm not sure if we should use `io::SeekFrom` itself as the documenntation for it specifically say that the values refer to byte offsets, whereas ours would refer to sample offsets.

**Comment by zyvitski** [comment]
I would just make a new enumerated unless there is a compelling reason to use the other?

**Comment by mitchmindtree** [comment]
Yes, apologies, I meant to say "I don't think we should" rather than "I'm not sure if we should".

**Comment by ruuda** [comment]
I am tempted to say that simpler is better. For any kind of audio player, would probably need to track the time or sample number anyway, so you can use that to compute a relative offset.

**Comment by mitchmindtree** [comment]
@ruuda I've added a commit that changes the implementation to work via duration rather than length. The docs and tests have been updated accordingly.

**Comment by ruuda** [comment]
Thanks! Should I make a new release for this?

**Comment by mitchmindtree** [comment]
@ruuda that would be much appreciated! 😌

**Comment by ruuda** [comment]
Hound v3.3.0, which includes this change, is now on crates.io. I renamed the method to just `seek` to avoid confusion about what constitutes a sample.

**Pull request merged**
